package bridge.implementacao;

import javax.swing.JPanel;


/**
 * Esta classe é específica para desenhar o Panel que descreve os Serviços Oferecidos na Uruguai
 * Como ela foi desenhada utilizando o Netbeans existe algum código gerado automaticamente que não está comentado.
 * @author silvap
 */
public class Chile extends JPanel implements DestinoImp {

    /**
     * Creates new form Argentina
     */
    public Chile() {
        initComponents();
        updateValor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkTranslado = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        checkGuia = new javax.swing.JCheckBox();
        checkSki = new javax.swing.JCheckBox();
        lblPreco = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spinnerHospedes = new javax.swing.JSpinner();
        comboBoxQuarto = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelFoto2 = new javax.swing.JLabel();
        labelFoto1 = new javax.swing.JLabel();
        labelBandera = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1024, 375));
        setMinimumSize(new java.awt.Dimension(1024, 375));
        setPreferredSize(new java.awt.Dimension(1024, 375));

        checkTranslado.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        checkTranslado.setText("Translado");
        checkTranslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTransladoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Neve no Chile");

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hotel Pinochet");

        checkGuia.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        checkGuia.setText("Guia");
        checkGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGuiaActionPerformed(evt);
            }
        });

        checkSki.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        checkSki.setText("Ski");
        checkSki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSkiActionPerformed(evt);
            }
        });

        lblPreco.setFont(new java.awt.Font("Liberation Serif", 0, 36)); // NOI18N
        lblPreco.setText("Total: $");

        jLabel5.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        jLabel5.setText("Inclui:");

        jLabel6.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        jLabel6.setText("Hóspedes:");

        jLabel8.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        jLabel8.setText("Acomodação:");

        spinnerHospedes.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        spinnerHospedes.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));
        spinnerHospedes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerHospedesStateChanged(evt);
            }
        });

        comboBoxQuarto.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        comboBoxQuarto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Suite", "Suite + Lareira", "Executivo" }));
        comboBoxQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxQuartoActionPerformed(evt);
            }
        });

        jLabel9.setText("Café da Manhã");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel10.setText("Massagem");

        jLabel11.setText("Piscina");

        jLabel13.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        jLabel13.setText("Opcionais:");

        labelFoto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chile1.jpg"))); // NOI18N
        labelFoto2.setToolTipText("");

        labelFoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chile2.jpg"))); // NOI18N

        labelBandera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chile3.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spinnerHospedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(checkTranslado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkSki)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkGuia)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPreco)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 510, Short.MAX_VALUE)
                        .addComponent(labelBandera)
                        .addGap(114, 114, 114))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(labelFoto1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelFoto2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(comboBoxQuarto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spinnerHospedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(62, 62, 62)
                                    .addComponent(jLabel6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(checkTranslado)
                            .addComponent(checkSki)
                            .addComponent(checkGuia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(lblPreco))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFoto1)
                            .addComponent(labelFoto2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelBandera)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxQuartoActionPerformed
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_comboBoxQuartoActionPerformed

    private void checkTransladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTransladoActionPerformed
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_checkTransladoActionPerformed

    private void checkSkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSkiActionPerformed
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_checkSkiActionPerformed

    private void checkGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGuiaActionPerformed
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_checkGuiaActionPerformed

    private void spinnerHospedesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerHospedesStateChanged
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_spinnerHospedesStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkGuia;
    private javax.swing.JCheckBox checkSki;
    private javax.swing.JCheckBox checkTranslado;
    private javax.swing.JComboBox comboBoxQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelBandera;
    private javax.swing.JLabel labelFoto1;
    private javax.swing.JLabel labelFoto2;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JSpinner spinnerHospedes;
    // End of variables declaration//GEN-END:variables


     @Override
    public String getServico() {
        int hospedes = (int) spinnerHospedes.getValue();
        String tipo_quarto = (String) comboBoxQuarto.getSelectedItem();
        String translado = checkTranslado.isSelected() ? "+ Translado<br>" : "";
        String ski = checkSki.isSelected() ? "+ Ski<br>" : "";
        String guia = checkGuia.isSelected() ? "+ Guia<br>" : "";
        
        String retorno = "Pais: Chile<br>";
        retorno += "Numero de Hospedes: " + hospedes + "<br>";
        retorno += "Tipo de Quarto" + tipo_quarto + "<br>";
        retorno += "Inclui:<br>";
        retorno += "Café da manhã<br>";
        retorno += "Massagem<br>";
        retorno += "Piscina<br>";
        retorno += "Opcionais:<br>";
        retorno += translado + ski + guia;
        retorno += "<br>Total: $"+updateValor()+"<br>";
        limpar();
        return retorno;
    }

    @Override
    public String getNome() {
        return "Chile";
    }

    private double updateValor() {
         int hospedes = (int) spinnerHospedes.getValue();
         String tipo_quarto = (String) comboBoxQuarto.getSelectedItem();
         double preco  = 0;
         switch(tipo_quarto){
             case "Suite":
                 preco = 45;
                 break;
             case "Suite + Lareira":
                 preco = 95;
                 break;
             case "Executivo":
                 preco = 220;
                 break;
         }
         
         double translado = checkTranslado.isSelected() ? 20 : 0;
         double ski = checkSki.isSelected() ? 35 : 0;
         double guia = checkGuia.isSelected() ? 15 : 0;
         
         double total = preco*hospedes + translado + ski + guia;
         
         lblPreco.setText(("Total $"+total));
         return total;
    }
    
    private void limpar(){
        spinnerHospedes.setValue(1);
        checkTranslado.setSelected(false);
        checkSki.setSelected(false);
        checkGuia.setSelected(false);
        updateValor();
    }

    @Override
    public JPanel getPanel() {
        return this;
    }
}
