package bridge.implementacao;

import bridge.implementacao.DestinoImp;
import javax.swing.JPanel;


/**
 * Esta classe é específica para desenhar o Panel que descreve os Serviços Oferecidos na Peru
 * Como ela foi desenhada utilizando o Netbeans existe algum código gerado automaticamente que não está comentado.
 * @author silvap
 */
public class Peru extends JPanel implements DestinoImp {

    /**
     * Creates new form Argentina
     */
    public Peru() {
        initComponents();
        updateValor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkMachuPichu = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        checkLavanderia = new javax.swing.JCheckBox();
        checkRefeicoes = new javax.swing.JCheckBox();
        lblPreco = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spinnerHospedes = new javax.swing.JSpinner();
        comboBoxQuarto = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelBandeira = new javax.swing.JLabel();
        labelFoto2 = new javax.swing.JLabel();
        labelFoto1 = new javax.swing.JLabel();
        labelFoto3 = new javax.swing.JLabel();
        labelFoto4 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1024, 375));
        setMinimumSize(new java.awt.Dimension(1024, 375));
        setPreferredSize(new java.awt.Dimension(1024, 375));

        checkMachuPichu.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        checkMachuPichu.setText("Machu Pichu");
        checkMachuPichu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMachuPichuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido a Peru!");

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hotel Noche Feliz");

        checkLavanderia.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        checkLavanderia.setText("Lavanderia");
        checkLavanderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLavanderiaActionPerformed(evt);
            }
        });

        checkRefeicoes.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        checkRefeicoes.setText("Refeições");
        checkRefeicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRefeicoesActionPerformed(evt);
            }
        });

        lblPreco.setFont(new java.awt.Font("Liberation Serif", 0, 36)); // NOI18N
        lblPreco.setText("Total: $");

        jLabel5.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        jLabel5.setText("Inclui:");

        jLabel6.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        jLabel6.setText("Hóspedes:");

        jLabel8.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        jLabel8.setText("Acomodação:");

        spinnerHospedes.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        spinnerHospedes.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));
        spinnerHospedes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerHospedesStateChanged(evt);
            }
        });

        comboBoxQuarto.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        comboBoxQuarto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simples", "Suite", "Executivo", "Presidencial" }));
        comboBoxQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxQuartoActionPerformed(evt);
            }
        });

        jLabel9.setText("Café da Manhã, translado do aereporto e piscina.");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel13.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        jLabel13.setText("Opcionais:");

        labelBandeira.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBandeira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/peru.jpg"))); // NOI18N

        labelFoto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/peru2.jpg"))); // NOI18N

        labelFoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/peru3.jpg"))); // NOI18N
        labelFoto1.setToolTipText("");

        labelFoto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/peru4.jpg"))); // NOI18N

        labelFoto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/peru5.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBandeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelFoto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelFoto3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelFoto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelFoto4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(36, 36, 36)
                                .addComponent(spinnerHospedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addComponent(jLabel5))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkMachuPichu)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkLavanderia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(checkRefeicoes)
                            .addGap(43, 43, 43)))
                    .addComponent(lblPreco))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBandeira)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFoto1)
                    .addComponent(labelFoto2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(spinnerHospedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(comboBoxQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(checkMachuPichu)
                            .addComponent(checkLavanderia)
                            .addComponent(checkRefeicoes))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(labelFoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblPreco)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxQuartoActionPerformed
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_comboBoxQuartoActionPerformed

    private void checkMachuPichuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMachuPichuActionPerformed
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_checkMachuPichuActionPerformed

    private void checkRefeicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRefeicoesActionPerformed
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_checkRefeicoesActionPerformed

    private void checkLavanderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLavanderiaActionPerformed
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_checkLavanderiaActionPerformed

    private void spinnerHospedesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerHospedesStateChanged
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_spinnerHospedesStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkLavanderia;
    private javax.swing.JCheckBox checkMachuPichu;
    private javax.swing.JCheckBox checkRefeicoes;
    private javax.swing.JComboBox comboBoxQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelBandeira;
    private javax.swing.JLabel labelFoto1;
    private javax.swing.JLabel labelFoto2;
    private javax.swing.JLabel labelFoto3;
    private javax.swing.JLabel labelFoto4;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JSpinner spinnerHospedes;
    // End of variables declaration//GEN-END:variables


     @Override
    public String getServico() {
        int hospedes = (int) spinnerHospedes.getValue();
        String tipo_quarto = (String) comboBoxQuarto.getSelectedItem();
        String machu = checkMachuPichu.isSelected() ? "+ Machu Pichu<br>" : "";
        String lavanderia = checkRefeicoes.isSelected() ? "+ Lavanderia<br>" : "";
        String refeicoes = checkLavanderia.isSelected() ? "+ Refeições<br>" : "";
        
        String retorno = "Pais: Peru<br>";
        retorno += "Numero de Hospedes: " + hospedes + "<br>";
        retorno += "Tipo de Quarto" + tipo_quarto + "<br>";
        retorno += "Inclui:<br>";
        retorno += "Café da Manhã, translado do aereporto e piscina.<br>";
        retorno += "Opcionais:<br>";
        retorno += machu + lavanderia + refeicoes;
        retorno += "<br>Total: $"+updateValor()+"<br>";
        limpar();
        return retorno;
    }

    @Override
    public String getNome() {
        return "Peru";
    }

    private double updateValor() {
         int hospedes = (int) spinnerHospedes.getValue();
         String tipo_quarto = (String) comboBoxQuarto.getSelectedItem();
         double preco  = 0;
         //Simples, Suite, Executivo, Presidencial,  
         switch(tipo_quarto){
             case "Simples":
                 preco = 25;
                 break;
             case "Suite":
                 preco = 45;
                 break;
             case "Executivo":
                 preco = 90;
                 break;
            case "Presidencial":
                 preco = 215;
                 break;
         }
         
         double machu = checkMachuPichu.isSelected() ? 20 : 0;
         double lavanderia = checkRefeicoes.isSelected() ? 35 : 0;
         double refeicoes = checkLavanderia.isSelected() ? 15 : 0;
         
         double total = preco*hospedes + machu + lavanderia + refeicoes;
         
         lblPreco.setText(("Total $"+total));
         return total;
    }
    
    private void limpar(){
        spinnerHospedes.setValue(1);
        checkMachuPichu.setSelected(false);
        checkRefeicoes.setSelected(false);
        checkLavanderia.setSelected(false);
        updateValor();
    }

    @Override
    public JPanel getPanel() {
        return this;
    }
}
