package bridge.implementacao;

import javax.swing.JPanel;



/**
 * Esta classe é específica para desenhar o Panel que descreve os Serviços Oferecidos na Argentina
 * Como ela foi desenhada utilizando o Netbeans existe algum código gerado automaticamente que não está comentado.
 * @author silvap
 */
public class Argentina extends JPanel implements DestinoImp {

    /**
     * Creates new form Argentina
     */
    public Argentina() {
        initComponents();
        updateValor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkInternet = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        labelBandeira = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        checkPiscina = new javax.swing.JCheckBox();
        checkSpa = new javax.swing.JCheckBox();
        checkTango = new javax.swing.JCheckBox();
        lblPreco = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spinnerAdultos = new javax.swing.JSpinner();
        spinnerCriancas = new javax.swing.JSpinner();
        comboBoxQuarto = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1024, 375));
        setMinimumSize(new java.awt.Dimension(1024, 375));
        setPreferredSize(new java.awt.Dimension(1024, 375));

        checkInternet.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        checkInternet.setText("Internet");
        checkInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInternetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" VISITE A ARGENTINA");

        labelBandeira.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBandeira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/argentina.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hotel Royal Moby");

        checkPiscina.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        checkPiscina.setText("Piscina Privativa");
        checkPiscina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPiscinaActionPerformed(evt);
            }
        });

        checkSpa.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        checkSpa.setText("Spa");
        checkSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSpaActionPerformed(evt);
            }
        });

        checkTango.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        checkTango.setText("Aula de Tango");
        checkTango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTangoActionPerformed(evt);
            }
        });

        lblPreco.setFont(new java.awt.Font("Liberation Serif", 0, 36)); // NOI18N
        lblPreco.setText("Total: $");

        jLabel5.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        jLabel5.setText("Inclui:");

        jLabel6.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        jLabel6.setText("Adultos:");

        jLabel7.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        jLabel7.setText("Crianças:");

        jLabel8.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        jLabel8.setText("Tipo do Quarto:");

        spinnerAdultos.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        spinnerAdultos.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        spinnerAdultos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerAdultosStateChanged(evt);
            }
        });

        spinnerCriancas.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        spinnerCriancas.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        spinnerCriancas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerCriancasStateChanged(evt);
            }
        });

        comboBoxQuarto.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        comboBoxQuarto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simples", "Duplo", "Triplo", "Casa" }));
        comboBoxQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxQuartoActionPerformed(evt);
            }
        });

        jLabel9.setText("Café da manhã, Serviço de Quarto, Toalhas e Lavanderia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(labelBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(24, 24, 24)
                                .addComponent(spinnerAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerCriancas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBoxQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE))))
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPreco)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkInternet)
                                    .addComponent(checkSpa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkPiscina)
                                    .addComponent(checkTango))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(spinnerCriancas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(spinnerAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(comboBoxQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(labelBandeira))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkInternet)
                    .addComponent(checkTango))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkSpa)
                    .addComponent(checkPiscina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPreco)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void spinnerAdultosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerAdultosStateChanged
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_spinnerAdultosStateChanged

    private void spinnerCriancasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerCriancasStateChanged
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_spinnerCriancasStateChanged

    private void comboBoxQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxQuartoActionPerformed
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_comboBoxQuartoActionPerformed

    private void checkInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInternetActionPerformed
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_checkInternetActionPerformed

    private void checkSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSpaActionPerformed
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_checkSpaActionPerformed

    private void checkTangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTangoActionPerformed
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_checkTangoActionPerformed

    private void checkPiscinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPiscinaActionPerformed
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_checkPiscinaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkInternet;
    private javax.swing.JCheckBox checkPiscina;
    private javax.swing.JCheckBox checkSpa;
    private javax.swing.JCheckBox checkTango;
    private javax.swing.JComboBox comboBoxQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelBandeira;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JSpinner spinnerAdultos;
    private javax.swing.JSpinner spinnerCriancas;
    // End of variables declaration//GEN-END:variables

    
     @Override
    public String getServico() {
        int hospedes = (int) spinnerAdultos.getValue();
        int criancas = (int) spinnerCriancas.getValue();
        String tipo_quarto = (String) comboBoxQuarto.getSelectedItem();
        String internet = checkInternet.isSelected() ? "+ Internet<br>" : "";
        String spa = checkSpa.isSelected() ? "+ Spa<br>" : "";
        String tango = checkTango.isSelected() ? "+ Aula de Tango<br>" : "";
        String piscina = checkPiscina.isSelected() ? "+ Piscina Privativa<br>" : "";
        
        String retorno = "Pais: Argentina<br>";
        retorno += "Numero de Hospedes: " + hospedes + "<br>";
        retorno += "Numero de Crianças: " + criancas + "<br>";
        retorno += "Tipo de Quarto" + tipo_quarto + "<br>";
        retorno += "Inclui:<br>";
        retorno += "Café da manhã, Serviço de Quarto, Toalhas e Lavanderia<br>";
        retorno += "Opcionais:<br>";
        retorno += internet + spa + tango + piscina;
        retorno += "<br>Total: $"+updateValor()+"<br>";
        limpar();
        return retorno;
    }

    @Override
    public String getNome() {
        return "Argentina";
    }

    private double updateValor() {
         int hospedes = (int) spinnerAdultos.getValue();
         int criancas = (int) spinnerCriancas.getValue();
         String tipo_quarto = (String) comboBoxQuarto.getSelectedItem();
         double preco  = 0;
         //Simples, Duplo, Triplo, Casa
         boolean is_casa = false;
         switch(tipo_quarto){
             case "Simples":
                 preco = 27;
                 break;
             case "Duplo":
                 preco = 46;
                 break;
             case "Triplo":
                 preco = 103;
                 break;
             case "Casa":
                 is_casa = true;
                 break;
         }
         
         double internet = checkInternet.isSelected() ? 5 : 0;
          double spa = checkSpa.isSelected() ? 20 : 0;
         double tango = checkTango.isSelected() ? 15 : 0;
         double piscina = checkPiscina.isSelected() ? 20 : 0;
         
        
         
         double total = is_casa ? 600 : preco*hospedes + criancas*preco/2;
         total += internet + tango + spa + piscina;
         
         
         lblPreco.setText(("Total $"+total));
         return total;
    }
    
    private void limpar(){
        spinnerAdultos.setValue(1);
        spinnerCriancas.setValue(0);
        checkInternet.setSelected(false);
        checkSpa.setSelected(false);
        checkTango.setSelected(false);
        checkPiscina.setSelected(false);
        updateValor();
    }

    @Override
    public JPanel getPanel() {
        return this;
    }
}
