package bridge.implementacao;

import javax.swing.JPanel;


/**
 * Esta classe é específica para desenhar o Panel que descreve os Serviços Oferecidos na Uruguai
 * Como ela foi desenhada utilizando o Netbeans existe algum código gerado automaticamente que não está comentado.
 * @author silvap
 */
public class Uruguai extends JPanel implements DestinoImp {

    /**
     * Creates new form Argentina
     */
    public Uruguai() {
        initComponents();
        updateValor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkInternet = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        checkSauna = new javax.swing.JCheckBox();
        checkGolf = new javax.swing.JCheckBox();
        lblPreco = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spinnerHospedes = new javax.swing.JSpinner();
        comboBoxQuarto = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelBandeira = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1024, 375));
        setMinimumSize(new java.awt.Dimension(1024, 375));
        setPreferredSize(new java.awt.Dimension(1024, 375));

        checkInternet.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        checkInternet.setText("Internet");
        checkInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInternetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Uruguay");

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hotel Simón Bolivar");

        checkSauna.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        checkSauna.setText("Sauna");
        checkSauna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSaunaActionPerformed(evt);
            }
        });

        checkGolf.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        checkGolf.setText("Golf");
        checkGolf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGolfActionPerformed(evt);
            }
        });

        lblPreco.setFont(new java.awt.Font("Liberation Serif", 0, 36)); // NOI18N
        lblPreco.setText("Total: $");

        jLabel5.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        jLabel5.setText("Inclui:");

        jLabel6.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        jLabel6.setText("Hóspedes:");

        jLabel8.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        jLabel8.setText("Acomodação:");

        spinnerHospedes.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        spinnerHospedes.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        spinnerHospedes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerHospedesStateChanged(evt);
            }
        });

        comboBoxQuarto.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        comboBoxQuarto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simples", "Executivo", "Presidencial" }));
        comboBoxQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxQuartoActionPerformed(evt);
            }
        });

        jLabel9.setText("Café da manhã, almoço e jantar.");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel10.setText("Serviço de Quarto");

        jLabel11.setText("Piscina");

        labelBandeira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Uruguay.jpg"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        jLabel13.setText("Opcionais:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPreco)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spinnerHospedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(comboBoxQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel5)))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkInternet)
                                    .addComponent(checkSauna)
                                    .addComponent(jLabel13)
                                    .addComponent(checkGolf))
                                .addGap(83, 83, 83)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(labelBandeira)
                        .addGap(77, 77, 77))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelBandeira)
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinnerHospedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkInternet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkGolf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkSauna))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(comboBoxQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPreco)
                        .addGap(32, 32, 32))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxQuartoActionPerformed
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_comboBoxQuartoActionPerformed

    private void checkInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInternetActionPerformed
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_checkInternetActionPerformed

    private void checkGolfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGolfActionPerformed
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_checkGolfActionPerformed

    private void checkSaunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSaunaActionPerformed
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_checkSaunaActionPerformed

    private void spinnerHospedesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerHospedesStateChanged
        // TODO add your handling code here:
        updateValor();
    }//GEN-LAST:event_spinnerHospedesStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkGolf;
    private javax.swing.JCheckBox checkInternet;
    private javax.swing.JCheckBox checkSauna;
    private javax.swing.JComboBox comboBoxQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelBandeira;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JSpinner spinnerHospedes;
    // End of variables declaration//GEN-END:variables


    @Override
    public String getServico() {
        int hospedes = (int) spinnerHospedes.getValue();
        String tipo_quarto = (String) comboBoxQuarto.getSelectedItem();
        String internet = checkInternet.isSelected() ? "+ Internet<br>" : "";
        String golf = checkGolf.isSelected() ? "+ Golf<br>" : "";
        String sauna = checkSauna.isSelected() ? "+ Sauna<br>" : "";
        
        
        String retorno = "Pais: Uruguai<br>";
        retorno += "Numero de Hospedes: " + hospedes + "<br>";
        retorno += "Tipo de Quarto" + tipo_quarto + "<br>";
        retorno += "Inclui:<br>";
        retorno += "Café da manhã, almoço e jantar.<br>";
        retorno += "Serviço de Quarto<br>";
        retorno += "Piscina<br>";
        retorno += "Opcionais:<br>";
        retorno += internet + sauna + golf;
        retorno += "<br>Total: $"+updateValor()+"<br>";
        limpar();
        return retorno;
    }

    @Override
    public String getNome() {
        return "Uruguai";
    }

    private double updateValor() {
         int hospedes = (int) spinnerHospedes.getValue();
         String tipo_quarto = (String) comboBoxQuarto.getSelectedItem();
         double preco  = 0;
         switch(tipo_quarto){
             case "Simples":
                 preco = 30;
                 break;
             case "Executivo":
                 preco = 60;
                 break;
             case "Presidencial":
                 preco = 110;
                 break;
         }
         
         double internet = checkInternet.isSelected() ? 5 : 0;
         double golf = checkGolf.isSelected() ? 20 : 0;
         double sauna = checkSauna.isSelected() ? 15 : 0;
         
         
         double total = preco*hospedes + internet + sauna + golf;
         
         lblPreco.setText(("Total $"+total));
         return total;
    }
    
    private void limpar(){
        spinnerHospedes.setValue(1);
        checkInternet.setSelected(false);
        checkGolf.setSelected(false);
        checkSauna.setSelected(false);
        updateValor();
    }

    @Override
    public JPanel getPanel() {
        return this;
    }
}
